name: KiBot

on:
  push:
    branches:
    - main
    paths:
    - 'kicad/**'
    - '.github/workflows/kibot.yaml'
  pull_request:
    paths:
    - 'kicad/**'
    - '.github/workflows/kibot.yaml'

jobs:
  kibot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:latest@sha256:e245e360a0739bfe5fec64856f8a9c154e875706a132621545cd15d232ed6a87
    steps:
    - uses: actions/checkout@v4
    - name: Cache 3D models data
      id: models-cache
      uses: set-soft/cache@main
      with:
        path: ~/cache_3d
        key: cache_3d
    - name: KiBot
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kicad/config.kibot.yaml
        schema: kicad/sneksafe.kicad_sch
        board: kicad/sneksafe.kicad_pcb
        cache3D: YES
        dir: Generated
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: KiBot
        path: Generated
