name: Delete Kiri Page on PR Close

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    types:
    - closed

jobs:
  kiri-delete:
    runs-on: ubuntu-22.04
    steps:
    - name: Kiri
      uses: usa-reddragon/kiri-github-action@v1
