name: Firmware Build Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=esphome/esphome
  ESPHOME_VERSION: 2024.6.4

on:
  push:
    paths:
    - firmware/**
    - .github/workflows/pr-firmware.yaml
  pull_request:

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: esphome/build-action@v3.2.0
      with:
        yaml_file: firmware/sneksafe.esphome.yaml
        version: ${{ env.ESPHOME_VERSION }}
