name: Release Firmware

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    uses: ./.github/workflows/reusable-build-firmware.yaml

  create-release:
    runs-on: ubuntu-latest
    needs: build-firmware

    steps:
    - uses: actions/checkout@v4

    - name: Set Versions
      run: |
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
      id: versions

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.versions.outputs.FIRMWARE_VERSION }}
        release_name: "SnekSafe ${{ steps.versions.outputs.FIRMWARE_VERSION }}"
        draft: false
        prerelease: false

    - name: Save release upload url to artifacts
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > upload_url

    - uses: actions/upload-artifact@v3
      with:
        name: upload_url
        path: upload_url
        if-no-files-found: error
        retention-days: 1

  upload-release:
    runs-on: ubuntu-latest
    needs: create-release

    strategy:
      matrix:
        platform:
        - esp32

    steps:
    - uses: actions/checkout@v4

    - name: Copy upload url
      uses: actions/download-artifact@v3
      with:
        name: upload_url

    - name: Set Versions
      run: |
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
        echo "UPLOAD_URL=$(cat upload_url)" >> $GITHUB_OUTPUT
      id: versions

    - name: Copy built frontend
      uses: actions/download-artifact@v3
      with:
        name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-frontend.bin

    - name: Copy built firmware
      uses: actions/download-artifact@v3
      with:
        name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-firmware.bin

    - name: Upload Firmware
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.versions.outputs.UPLOAD_URL }}
        asset_path: firmware.bin
        asset_name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-firmware.bin
        asset_content_type: application/octet-stream

    - name: Upload Frontend
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.versions.outputs.UPLOAD_URL }}
        asset_path: littlefs.bin
        asset_name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-frontend.bin
        asset_content_type: application/octet-stream
