name: Release Firmware

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=esphome/esphome
  ESPHOME_VERSION: 2024.8.3

jobs:
  build-firmware:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set Versions
      run: |
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
      id: versions

    - uses: esphome/build-action@9dcc9e036539b3dfc83dc3489f958999ea035efb # v3.3.0
      id: build
      with:
        yaml_file: firmware/sneksafe.esphome.yaml
        version: ${{ env.ESPHOME_VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.versions.outputs.FIRMWARE_VERSION }}
        release_name: "SnekSafe ${{ steps.versions.outputs.FIRMWARE_VERSION }}"
        draft: false
        prerelease: false

    - name: Upload Firmware
      uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.name }}/${{ steps.build.outputs.name }}.bin
        asset_name: SnekSafe-esp32-${{ steps.versions.outputs.FIRMWARE_VERSION }}-firmware.bin
        asset_content_type: application/octet-stream
