name: Release Firmware

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=esphome/esphome
  ESPHOME_VERSION: 2024.6.1

jobs:
  build-firmware:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set Versions
      run: |
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
      id: versions

    - uses: esphome/build-action@v2.0.1
      id: build
      with:
        yaml_file: firmware/sneksafe.esphome.yaml
        version: ${{ env.ESPHOME_VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.versions.outputs.FIRMWARE_VERSION }}
        release_name: "SnekSafe ${{ steps.versions.outputs.FIRMWARE_VERSION }}"
        draft: false
        prerelease: false

    - name: Upload Firmware
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.name }}/${{ steps.build.outputs.name }}.bin
        asset_name: SnekSafe-esp32-${{ steps.versions.outputs.FIRMWARE_VERSION }}-firmware.bin
        asset_content_type: application/octet-stream
