name: Release Firmware

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware.yaml

  create-release:
    runs-on: ubuntu-latest
    needs: build-firmware

    steps:
    - uses: actions/checkout@v3

    - name: Set Versions
      run: |
        echo "FRONTEND_VERSION=$(cat frontend/package.json | jq -r .version)" >> $GITHUB_OUTPUT
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
      id: versions

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.versions.outputs.FIRMWARE_VERSION }}-${{ github.run_number }}
        release_name: "SnekSafe FW ${{ steps.versions.outputs.FIRMWARE_VERSION }}, FE v${{ steps.versions.outputs.FRONTEND_VERSION }} Build #${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Save release upload url to artifacts
      run: |
        echo "RELEASE_UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" > upload_url

    - uses: actions/upload-artifact@v3
      with:
        name: upload_url
        path: upload_url
        if-no-files-found: error
        retention-days: 1

  upload-release:
    runs-on: ubuntu-latest
    needs: create-release

    strategy:
      matrix:
        platform:
        - esp32
        - esp32dev

    steps:
    - uses: actions/checkout@v3

    - name: Copy built frontend
      uses: actions/download-artifact@v3
      with:
        name: upload_url
        path: upload_url

    - name: Set Versions
      run: |
        echo "FRONTEND_VERSION=$(cat frontend/package.json | jq -r .version)" >> $GITHUB_OUTPUT
        echo "FIRMWARE_VERSION=$(cat firmware/.version)" >> $GITHUB_OUTPUT
        echo "UPLOAD_URL=$(cat upload_url)" >> $GITHUB_OUTPUT
      id: versions

    - name: Copy built frontend
      uses: actions/download-artifact@v3
      with:
        name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FRONTEND_VERSION }}-${{ github.run_number }}-frontend.bin
        path: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FRONTEND_VERSION }}-${{ github.run_number }}-frontend.bin

    - name: Copy built firmware
      uses: actions/download-artifact@v3
      with:
        name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-${{ github.run_number }}-firmware.bin
        path: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-${{ github.run_number }}-firmware.bin

    - name: Upload Firmware
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.versions.outputs.UPLOAD_URL }}
        asset_path: firmware/.pio/build/${{ matrix.platform }}/firmware.bin
        asset_name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FIRMWARE_VERSION }}-${{ github.run_number }}-firmware.bin
        asset_content_type: application/octet-stream

    - name: Upload Frontend
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.versions.outputs.UPLOAD_URL }}
        asset_path: firmware/.pio/build/${{ matrix.platform }}/littlefs.bin
        asset_name: SnekSafe-${{ matrix.platform }}-${{ steps.versions.outputs.FRONTEND_VERSION }}-${{ github.run_number }}-frontend.bin
        asset_content_type: application/octet-stream
